//smartnet_sync.cc
/* -*- c++ -*- */
/*
 * Copyright 2004 Free Software Foundation, Inc.
 * 
 * This file is part of GNU Radio
 * 
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 * 
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */

/*
 * config.h is generated by configure.  It contains the results
 * of probing for features, options etc.  It should be the first
 * file included in your .cc file.
 */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "smartnet_sync.h"
#include <gr_io_signature.h>
#include <sstream>

/*
 * Create a new instance of smartnet_sync and return
 * a boost shared_ptr.  This is effectively the public constructor.
 */
smartnet_sync_sptr smartnet_make_sync()
{
  return smartnet_sync_sptr (new smartnet_sync ());
}

/*
 * Specify constraints on number of input and output streams.
 * This info is used to construct the input and output signatures
 * (2nd & 3rd args to gr_block's constructor).  The input and
 * output signatures are used by the runtime system to
 * check that a valid number and type of inputs and outputs
 * are connected to this block.  In this case, we accept
 * only 1 input and 1 output.
 */
static const int MIN_IN = 1;    // mininum number of input streams
static const int MAX_IN = 1;    // maximum number of input streams
static const int MIN_OUT = 1;   // minimum number of output streams
static const int MAX_OUT = 1;   // maximum number of output streams

/*
 * The private constructor
 */
smartnet_sync::smartnet_sync ()
  : gr_sync_block ("sync",
                   gr_make_io_signature (MIN_IN, MAX_IN, sizeof (char)),
                   gr_make_io_signature (MIN_OUT, MAX_OUT, sizeof (char)))
{
  // nothing else required in this example
	set_output_multiple(84);
}

/*
 * Our virtual destructor.
 */
smartnet_sync::~smartnet_sync ()
{
  // nothing else required in this example
}

int 
smartnet_sync::work (int noutput_items,
                        gr_vector_const_void_star &input_items,
                        gr_vector_void_star &output_items)
{
  const char *in = (const char *) input_items[0];
  char *out = (char *) output_items[0];

	//iterate over all output items
	//if you get one with a correlator trigger, if there's 84 more left in the queue, if the 84th one on also has a trigger, then it's good! otherwise clear it cause it's a false flag

	for(int i=0; i < noutput_items; i++) {
		if(in[i] & 0x02) {
			if(noutput_items-i >= 84) {
				if(in[i+84] & 0x02) out[i] = in[i];
				else out[i] = in[i] & 0x01;
			} else return i; //weren't enough to validate it, so go back for more
		} else out[i] = in[i];

	}

  // Tell runtime system how many output items we produced.
  return noutput_items;
}

