//smartnet_crc.cc
/* -*- c++ -*- */
/*
 * Copyright 2004 Free Software Foundation, Inc.
 * 
 * This file is part of GNU Radio
 * 
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 * 
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */

/*
 * config.h is generated by configure.  It contains the results
 * of probing for features, options etc.  It should be the first
 * file included in your .cc file.
 */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "smartnet_crc.h"
#include <gr_io_signature.h>
#include <stdio.h>

/*
 * Create a new instance of smartnet_crc and return
 * a boost shared_ptr.  This is effectively the public constructor.
 */
smartnet_crc_sptr smartnet_make_crc()
{
  return smartnet_crc_sptr (new smartnet_crc ());
}

/*
 * Specify constraints on number of input and output streams.
 * This info is used to construct the input and output signatures
 * (2nd & 3rd args to gr_block's constructor).  The input and
 * output signatures are used by the runtime system to
 * check that a valid number and type of inputs and outputs
 * are connected to this block.  In this case, we accept
 * only 1 input and 1 output.
 */
static const int MIN_IN = 1;    // mininum number of input streams
static const int MAX_IN = 1;    // maximum number of input streams
static const int MIN_OUT = 1;   // minimum number of output streams
static const int MAX_OUT = 1;   // maximum number of output streams

/*
 * The private constructor
 */
smartnet_crc::smartnet_crc ()
  : gr_sync_block ("crc",
                   gr_make_io_signature (MIN_IN, MAX_IN, sizeof (char)),
                   gr_make_io_signature (MIN_OUT, MAX_OUT, sizeof (char)))
{
  // nothing else required in this example
	set_output_multiple(38);
}

/*
 * Our virtual destructor.
 */
smartnet_crc::~smartnet_crc ()
{
  // nothing else required in this example
}

int 
smartnet_crc::work (int noutput_items,
                        gr_vector_const_void_star &input_items,
                        gr_vector_void_star &output_items)
{
  const char *in = (const char *) input_items[0];
  char *out = (char *) output_items[0];

  int i = 0;
  unsigned int crcaccum;
  unsigned int crcop;
  unsigned int crcgiven;

  while(i < noutput_items) {
	while(!(in[i] & 0x02)) i++; //skip until the start bit is found
	if((noutput_items-i) < 38) return i;

	crcaccum = 0x0393;
	crcop = 0x036E;

	//now we're at the start of a 38-bit frame, so calculate the expected crc
	for(int j = 0; j < 27; j++) {
		if (crcop & 0x01) crcop = (crcop >> 1) ^ 0x0225; else crcop = crcop >> 1;
		if (in[i+j] & 0x01) crcaccum = crcaccum ^ crcop;
	}

	//now we load up the GIVEN crc value
	crcgiven = 0x0000;
	for(int j = 0; j < 10; j++) {
		crcgiven <<= 1;
		crcgiven += !bool(in[i+j+27] & 0x01);
	}

	if(crcgiven != crcaccum) printf("Failed CRC!\n");	

	for(int j = 0; j < 38; j++) {
		if(crcgiven == crcaccum) out[j+i] = in[j+i];
		else out[j+i] = in[j+i] & 0x01;
	}

	i += 38;
  }

  // Tell runtime system how many output items we produced.
  return noutput_items;
}

